name: Run Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install -g yarn
      name: Install Yarn
    - run: yarn install
      name: Install dependencies
    - run: yarn test
      name: Run tests
      
      env:
        CI: true
